- name: Import ES key
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present

- name: Add repository
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/5.x/apt stable main
    state: present

- name: Install required packages
  apt:
    name: '{{ item }}'
    state: present
  with_items:
    - default-jdk
    - elasticsearch
